import {Navbar} from "@/components/Navbar";
import {SectionHeading} from "@/components/SectionHeading";
import {ProjectGrid} from "@/components/ProjectGrid";
import {ContactForm} from "@/components/ContactForm";
import {ContentEmbeds} from "@/components/ContentEmbeds";
import {portfolio} from "@/data/portfolio";
const X=({href,children}:{href:string;children:React.ReactNode})=><a className="link" href={href} target="_blank" rel="noreferrer">{children}</a>;
export default function Home(){const p=portfolio,s=p.socials;return <main id="top"><Navbar/><script
  type="application/ld+json"
  dangerouslySetInnerHTML={{
    __html: JSON.stringify({
      "@context": "https://schema.org",
      "@type": "Person",
      name: p.profile.name,
      jobTitle: p.profile.title,
      email: `mailto:${p.profile.email}`,
      address: {
        "@type": "PostalAddress",
        addressLocality: "Greater Noida",
        addressRegion: "Uttar Pradesh",
        addressCountry: "IN"
      },
      alumniOf: {
        "@type": "CollegeOrUniversity",
        name: p.education.institution
      },
      sameAs: [
        s.linkedin,
        s.github,
        s.gitlab,
        s.x,
        s.threads,
        s.leetcode,
        s.codeforces,
        s.instagram,
        s.youtube
      ]
    })
  }}
/>
<section className="relative overflow-hidden border-b border-slate-200 dark:border-slate-800"><div className="hero-grid absolute inset-0 -z-10 opacity-60"/><div className="mx-auto grid min-h-[76vh] max-w-7xl items-center gap-10 px-5 py-14 sm:py-16 lg:grid-cols-[1.25fr_.75fr] lg:px-8 lg:py-20"><div><span className="inline-flex items-center gap-2 rounded-full border border-teal-200 bg-teal-50 px-3 py-1.5 text-sm font-bold text-teal-700 dark:border-teal-900 dark:bg-teal-950/50 dark:text-teal-300"><i className="h-2 w-2 rounded-full bg-teal-500"/>Available immediately</span><p className="mt-6 font-semibold text-slate-500">Hi, I’m {p.profile.name}.</p><h1 className="mt-3 max-w-5xl text-4xl font-black leading-[1.06] tracking-[-.04em] sm:text-6xl lg:text-7xl">I build <span className="text-teal-600 dark:text-teal-400">full-stack products</span> that solve real problems.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">{p.profile.intro}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#projects" className="btn-primary">View Projects</a>{p.profile.resumeUrl&&<a href={p.profile.resumeUrl} className="btn-secondary" download>Download Resume</a>}<a href="#contact" className="btn-secondary">Contact Me</a></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-500"><span>📍 {p.profile.location}</span><span>💼 {p.profile.workPreference}</span><span>✈ {p.profile.relocation}</span></div></div><div className="mx-auto w-full max-w-md rounded-[2.25rem] border border-slate-200 bg-white p-7 shadow-xl dark:border-slate-800 dark:bg-slate-900">{p.profile.profileImage ? <img src={p.profile.profileImage} alt={p.profile.name} className="aspect-square w-full rounded-[1.8rem] object-cover object-top" /> : <div className="flex aspect-square items-center justify-center rounded-[1.8rem] bg-gradient-to-br from-teal-500 to-cyan-700 text-7xl font-black text-white">DV</div>}<h2 className="mt-6 text-2xl font-black">{p.profile.name}</h2><p className="mt-1 font-bold text-teal-600 dark:text-teal-400">{p.profile.title}</p><p className="mt-4 text-sm leading-6 text-slate-500">React · Next.js · Node.js · PostgreSQL · Supabase · MongoDB · Java</p></div></div></section>
<section id="about" className="section"><SectionHeading eyebrow="About" title="Building, learning, and contributing."/><div className="grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><div className="card space-y-4 text-lg leading-8 text-slate-600 dark:text-slate-300">{p.about.map(t=><p key={t}>{t}</p>)}</div><div className="grid gap-4">{[["6","Featured projects"],["110+","LeetCode problems"],["10K","Top reel reach"]].map(([v,l])=><div className="card" key={l}><p className="text-3xl font-black text-teal-600 dark:text-teal-400">{v}</p><p className="mt-1 text-sm text-slate-500">{l}</p></div>)}</div></div></section>
<section id="experience" className="section"><SectionHeading eyebrow="Experience" title="Professional experience."/><article className="card"><h3 className="text-2xl font-black">{p.experience.role}</h3><p className="mt-1 font-bold text-teal-600">{p.experience.company}</p><p className="mt-2 text-sm text-slate-500">{p.experience.dates} · {p.experience.location}</p><ul className="mt-6 grid gap-3 text-slate-600 dark:text-slate-300 md:grid-cols-2">{p.experience.bullets.map(b=><li className="flex gap-3" key={b}><span className="text-teal-500">✓</span>{b}</li>)}</ul><div className="mt-6"><X href={p.experience.repo}>View task dashboard repository ↗</X></div><p className="mt-4 text-xs text-slate-400">Experience letter available on request.</p></article></section>
<section id="projects" className="section"><SectionHeading eyebrow="Featured Projects" title="Work that shows how I build." copy="Selected full-stack, AI, SaaS, and computer-vision projects."/><ProjectGrid projects={p.projects}/></section>
<section id="opensource" className="section"><SectionHeading eyebrow="Open Source" title="Contributing beyond my own repositories."/><div className="grid gap-5 lg:grid-cols-3">{p.openSource.map(o=><article className="card" key={o.url}><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">{o.repo}</p><h3 className="mt-3 text-lg font-black">{o.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{o.detail}</p><div className="mt-5"><X href={o.url}>View merged PR ↗</X></div></article>)}</div></section>
<section id="skills" className="section"><SectionHeading eyebrow="Skills" title="Tools I use to ship software."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{Object.entries(p.skills).map(([g,a])=><article className="card" key={g}><h3 className="font-black">{g}</h3><div className="mt-4 flex flex-wrap gap-2">{a.map(x=><span className="chip" key={x}>{x}</span>)}</div></article>)}</div></section>
<section className="section"><SectionHeading eyebrow="Coding Profiles" title="Consistent problem-solving practice."/><div className="grid gap-5 md:grid-cols-2"><article className="card"><p className="font-bold text-teal-600">LeetCode</p><p className="mt-4 text-5xl font-black">{p.coding.leetcode.solved}</p><p className="mt-2 text-sm text-slate-500">Easy {p.coding.leetcode.easy} · Medium {p.coding.leetcode.medium} · Hard {p.coding.leetcode.hard} · {p.coding.leetcode.badge}</p><div className="mt-5"><X href={s.leetcode}>View LeetCode ↗</X></div></article><article className="card"><p className="font-bold text-teal-600">Codeforces</p><p className="mt-4 text-5xl font-black">{p.coding.codeforces.rating}</p><p className="mt-2 text-sm text-slate-500">{p.coding.codeforces.rank}</p><div className="mt-5"><X href={s.codeforces}>View Codeforces ↗</X></div></article></div></section>
<section id="achievements" className="section"><SectionHeading eyebrow="Achievements" title="Hackathons and validated milestones."/><div className="grid gap-5 md:grid-cols-2">{p.achievements.map(a=><article className="card" key={a.title}><p className="text-xs font-bold uppercase tracking-[.16em] text-teal-600">{a.organizer}</p><h3 className="mt-2 text-xl font-black">{a.title}</h3><p className="mt-3 text-slate-600 dark:text-slate-300">{a.result}</p></article>)}</div></section>
<section className="section"><SectionHeading eyebrow="Education" title="Computer Science + AI/ML."/><article className="card"><div className="flex flex-col justify-between gap-5 md:flex-row"><div><h3 className="text-2xl font-black">{p.education.degree}</h3><p className="mt-1 font-bold text-teal-600">{p.education.institution}</p><p className="mt-2 text-slate-500">{p.education.specialization} · {p.education.years}</p></div><div className="rounded-2xl bg-teal-50 px-5 py-3 text-center dark:bg-teal-950/50"><p className="text-xs font-bold text-teal-700">CGPA</p><p className="text-2xl font-black text-teal-700 dark:text-teal-300">{p.education.cgpa}</p></div></div><div className="mt-6 flex flex-wrap gap-2">{p.education.coursework.map(c=><span className="chip" key={c}>{c}</span>)}</div></article></section>
<section id="content" className="section"><SectionHeading eyebrow={p.content.brand} title="JavaScript and Three.js tech content." copy={p.content.description}/><div className="grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><article className="card h-fit"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold text-teal-600 dark:text-teal-400">Creator snapshot</p><h3 className="mt-2 text-2xl font-black">FutureRouteX</h3></div><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-700 dark:bg-teal-950/50 dark:text-teal-300">Tech Content</span></div><ul className="mt-6 space-y-3 text-slate-600 dark:text-slate-300">{p.content.stats.map(x=><li className="flex gap-3" key={x}><span className="text-teal-500">✓</span>{x}</li>)}</ul><div className="mt-7 flex flex-wrap gap-4"><X href={s.instagram}>Instagram ↗</X><X href={s.youtube}>YouTube ↗</X></div><p className="mt-6 text-sm leading-6 text-slate-500 dark:text-slate-400">Selected videos and Reels are embedded directly below so recruiters can preview the content without leaving the portfolio.</p></article><ContentEmbeds items={p.content.selected}/></div></section>
<section className="section"><SectionHeading eyebrow="Services" title="Available for selected projects."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{p.services.map(v=><div className="card font-semibold" key={v}>{v}</div>)}</div></section>
<section id="contact" className="section"><SectionHeading eyebrow="Contact" title="Let’s build something useful." copy="Open to Software Developer and Full Stack Developer opportunities, selected freelance projects, and technical collaborations."/><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="card"><p className="text-sm text-slate-500">Best direct contact</p><a className="mt-2 block break-all text-xl font-black text-teal-600" href={`mailto:${p.profile.email}`}>{p.profile.email}</a><div className="mt-7 grid gap-3"><X href={s.linkedin}>LinkedIn ↗</X><X href={s.github}>GitHub ↗</X><X href={s.x}>X ↗</X><X href={s.threads}>Threads ↗</X></div><p className="mt-8 rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-500 dark:bg-slate-800/60">No phone number, exact address, roll number, DOB, or private internship documents are published.</p></div><ContactForm/></div></section>
<footer className="border-t border-slate-200 py-8 dark:border-slate-800"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 px-5 text-sm text-slate-500 sm:flex-row lg:px-8"><p>© 2026 Deshraj Verma.</p><p>Next.js · TypeScript · Tailwind CSS</p></div></footer></main>}
